export const CURRENT_CATEGORY = "CURRENT_CATEGORY";
export const NEW_CATEGORY = "NEW_CATEGORY";
export const SELECT_CATEGORY = "SELECT_CATEGORY";
export const EDIT_CATEGORY = "EDIT_CATEGORY";
export const CLEAR_CATEGORY = "CLEAR_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";

export const GET_VIDEOS = "GET_VIDEOS";
export const NEW_VIDEO = "NEW_VIDEO";
